### ISSUE TITLE
Proposal: Change Repo name

### ISSUE THREAD

**Issue by frank-dspeed** [feathersjs/feathers-docker#1]
Hello it would be nice if we could change the Repo name to feathers-docker-playground or similar

i whant to publish feathers-docker a docker api integration for feathers.

greetings.

**Comment by daffl** [comment]
@ekryski Does this repo have to exist at all? Seems like this might work better as an article and some Gists?

**Comment by ekryski** [comment]
Nope it does not. Let's do it. I'll rename the repo to `feathers-devops-playground`.

**Comment by ekryski** [comment]
Done! @frank-dspeed stoked to see it! 😄

**Comment by frank-dspeed** [comment]
Thx a lot frinds
